name: myapp
description: A simple command-line application using Realm Dart SDK.

publish_to: none

environment:
  sdk: ^3.3.0

dependency_overrides:
  realm_generator:
    path: ../../realm_generator
  dart_style: 3.0.1
  source_gen: 2.0.0
  analyzer: 7.3.0

dependencies:
  realm_dart:
    path: ../

dev_dependencies:
  lints: ^3.0.0
